core/urls.py
from django.contrib import admin
from django.urls import path,include
from naija.views import HomePage, signup,logout_view
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home'),
    path('signup/', signup, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('solutions/',include('naija.urls', namespace='naija')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

naija/urls.py
from django.urls import path
from .views import *

app_name = 'naija'

urlpatterns = [
    path('list-solution/<int:pk>/', SolutionView.as_view(), name='list-solution'),
    path('create/', CreateSolutionView.as_view(),name='create'),
    path('vote/<int:pk>/', vote_solution_view, name='vote'),
    path('create-profile/<int:pk>/',ProfileCreateView.as_view(),name='create-profile'),
]

naija/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Problem(models.Model):
    problem_category = models.ForeignKey(Category,on_delete=models.CASCADE)
    title_of_problem = models.CharField(max_length=150)
    short_description = models.CharField(max_length=255,blank=True,null=True)

    def __str__(self):
        return self.title_of_problem

class Profile(models.Model):
    fullname = models.CharField(max_length=255)
    contact_email  = models.EmailField()
    account_number = models.CharField(max_length=10)
    bank = models.CharField(max_length=255)
    account_name = models.CharField(max_length=255)

    def __str__(self):
        return self.fullname
    
class Solution(models.Model):
    problem = models.ForeignKey(Problem,on_delete=models.CASCADE)
    solution_provider = models.ForeignKey(Profile,on_delete=models.SET_NULL,null=True,blank=True)
    solution_title = models.CharField(max_length=255, blank=True, null=True)
    solution_text = models.TextField()
    user_voted = models.ManyToManyField(get_user_model())

    def __str__(self):
        return self.solution_title

naija/forms.py
from django.forms import ModelForm
from .models import Profile, Solution

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['fullname','contact_email','account_number','bank','account_name']

class SolutionForm(ModelForm):
    class Meta:
        model = Solution
        fields = ['solution_title','solution_text']

naija/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate, get_user_model, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import TemplateView, FormView
from django.http import HttpResponseRedirect
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import redirect
from .models import *
from .forms import *

class HomePage(TemplateView):
    template_name = 'index.html'

    def get(self,request):
        problems = Problem.objects.all()
        template_data = {'problems':problems}
        
        return render(request, self.template_name, template_data)

class SolutionView(TemplateView):
    template_name = 'list-solution.html'

    def get(self,request,pk):
        solutions = Solution.objects.filter(problem__id=pk)
        template_data = {'solutions':solutions}

        return render(request, self.template_name, template_data)

class CreateSolutionView(FormView):
    template_name = 'create-solution.html'
    form_class = SolutionForm

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        title = form.cleaned_data['solution_title']
        body = form.cleaned_data['solution_text']
        profile_id = self.request.session['profile_id']
        problem_id = self.request.session['problem_id']

        profile = Profile.objects.get(id=profile_id)
        problem = Problem.objects.get(id=problem_id)
        Solution.objects.create(solution_provider=profile, problem=problem, solution_title=title, solution_text=body)

        messages.success(self.request, "Successful")
        return HttpResponseRedirect(f'/solutions/list-solution/{problem_id}/')

class ProfileCreateView(FormView):
    template_name = 'profile_form.html'
    form_class = ProfileForm

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        name = form.cleaned_data['fullname']
        email = form.cleaned_data['contact_email']
        acc_number = form.cleaned_data['account_number']
        bank = form.cleaned_data['bank']
        acct_name = form.cleaned_data['account_name']

        profile, created = Profile.objects.get_or_create(fullname=name,contact_email=email,account_number=acc_number,bank=bank,account_name=acct_name)
        self.request.session['profile_id'] = profile.id
        self.request.session['problem_id'] = self.kwargs['pk']
        return redirect('naija:create')
        # return super().form_valid(form)

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        success_url = request.GET.get('next','/')
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect(success_url)
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

def logout_view(request):
    success_url = request.GET.get('next','/')
    logout(request)
    return redirect(success_url)

@login_required(login_url='/login/')
def vote_solution_view(request,pk):
    success_url = request.GET.get('next','/')
    solution = Solution.objects.get(id=pk)
    solution.user_voted.add(request.user)
    solution.save()
    return redirect(success_url)

naija/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fix Nigeria</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>
  <!-- Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container-fluid">
          <a class="navbar-brand" href={% url 'home' %}>Fix Nigeria</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse " id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href={% url 'home' %}>Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href={% url 'logout' %}?next={{ request.path|urlencode }}>Sign out</a>
              </li>
              
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href={% url 'signup' %}?next={{ request.path|urlencode }}>Sign up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href={% url 'login' %}?next={{ request.path|urlencode }}>Sign in</a>
              </li>
              {% endif %}
            </ul>
            
          </div>
        </div>
      </nav><br>


      {% block content %}

      {% endblock %}
    <!-- JavaScript Bundle with Popper -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</body>
</html>

naija/templates/create-solution.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content %}
<h1>What's your solution?</h1>
<div class='container-fluid'>
  <form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    {% buttons %}
      <button type="submit" class="btn btn-outline-success">
        Submit
      </button>
    {% endbuttons %}
  </form>
</div>

{% endblock %}

naija/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <!-- Jumbotron Text -->
    <!-- <h1>Be one of the lucky winners this week!</h1> -->
    {% if problems %}
        {% for problem in problems %}
        <div class="card">
            <h5 class="card-header">{{ problem.problem_category }}</h5>
            <div class="card-body">
            <h5 class="card-title">{{ problem.title_of_problem }}</h5>
            {% if problem.short_description %}
            <p class="card-text">{{ problem.short_description }}</p>
            {% else %}
            <p class="card-text"></p>
            {% endif %}
            <a href={% url 'naija:create-profile' problem.id %} class="btn btn-outline-success">Start Solution</a>
            <a href={% url 'naija:list-solution' problem.id %} class="btn btn-outline-success">See Solutions</a>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <h1>Problem don finally finish</h1>
    {% endif %}
{% endblock %}

naija/templates/list-solution.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% bootstrap_messages %}

{% block content %}

{% if messages %}
<ul class="messages">
  {% for message in messages %}
  <li class = "alert alert-success" role="alert" >{{message}}</li>

  {% endfor %}
</ul>

{% endif %}

    {% if solutions %}
        {% for solution in solutions %}
            <div class="card">
                <div class="card-header">
                Number of votes: {{ solution.user_voted.all|length }}
                </div>
                
                <div class="card-body container">
                <h5 class="card-title">{{ solution.solution_title }}</h5>
                <p class="card-text" style="font-size:20px;" >{{ solution.solution_text }}</p>
                {% if user in solution.user_voted.all %}
                <span class="badge rounded-pill bg-danger">Voted</span>
                {% else %}
                <a href={% url 'naija:vote' solution.id %}?next={{ request.path|urlencode }} class="btn btn-success">Approve</a>
                {% endif %}
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No solutions yet</p>
    {% endif %}
{% endblock %}

naija/templates/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content %}
<h1>Sign In</h1>
<div class='container-fluid'>
  <form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    {% buttons %}
      <button type="submit" class="btn btn-outline-success">
        Sign In
      </button>
    {% endbuttons %}
  </form>
</div>

{% endblock %}

naija/templates/profile_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content %}
<h1>Fill this form to proceed</h1>
<div class='container-fluid'>
  <form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    {% buttons %}
      <button type="submit" class="btn btn-outline-success">
        Submit
      </button>
    {% endbuttons %}
  </form>
</div>

{% endblock %}

naija/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content %}
<h1>Sign Up</h1>
<div class='container-fluid'>
  <form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    {% buttons %}
      <button type="submit" class="btn btn-outline-success">
        Submit
      </button>
    {% endbuttons %}
  </form>
</div>

{% endblock %}